spring.application.name=TopografiaHernandez

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=TOPOGRAFIA
spring.datasource.password=Topo2026
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML

server.port=8081